apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-deployment
  namespace: prod-version
  labels:
    app: nginx
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "50%"
      maxSurge: "50%"
  selector:
    matchLabels:
      env: prod
      version: v1
  template:
    metadata:
      labels:
        env: prod
        version: v1
    spec:
      containers:
      - name: nginx-container
        image: nginx